"""empty message

Revision ID: 5f4081102aad
Revises: 
Create Date: 2026-09-25 13:17:47.742004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4081102aad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialty',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Enum('ophthalmology', 'optometry', 'pediatric eye care', 'glaucoma', 'cataract care', 'eye surgery'), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('specialty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_specialty_name'), ['name'], unique=False)

    op.create_table('doctors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=False),
    sa.Column('last_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('specialty_id', sa.Integer(), nullable=True),
    sa.Column('availability', sa.Enum('available', 'unavailable'), nullable=True),
    sa.Column('licence_number', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['specialty_id'], ['specialty.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('specialty_id')
    )
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_doctors_first_name'), ['first_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_doctors_first_name'))

    op.drop_table('doctors')
    with op.batch_alter_table('specialty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_specialty_name'))

    op.drop_table('specialty')
    # ### end Alembic commands ###
